New job ci
soapwaster/excel-checker pull request #10
Opened 2023-01-24 18:50 UTC by soapwaster

2023-01-24 19:20 UTC, angelocatalani requested changes
i think it is possible to reuse the steps

2023-01-25 10:44 UTC, soapwaster commented
lgty ?

2023-01-25 11:04 UTC, angelocatalani requested changes

2023-01-25 11:04 UTC, angelocatalani commented on .github/actions/poetry/action.yaml
> +description: 'Poetry install'
```suggestion
description: 'Build the application with Poetry'
```

2023-01-25 11:04 UTC, angelocatalani commented on .github/actions/poetry/action.yaml
> +name: 'Poetry Install'
```suggestion
name: 'Build application'
```

2023-01-25 11:04 UTC, angelocatalani commented on .github/actions/poetry/action.yaml
> +name: 'Poetry Install'
I think it is better to rename the subfolder to application and the the yaml to build.yaml

2023-01-25 11:04 UTC, angelocatalani commented on .github/actions/poetry/action.yaml
> +          shell: bash
missing new line

2023-01-25 11:04 UTC, angelocatalani commented on .github/workflows/main.yaml
> +      - id: deploy
```suggestion
      - id: build application
```

2023-01-25 11:04 UTC, angelocatalani commented on .github/workflows/main.yaml
> +      - id: deploy
```suggestion
      - id: build application
```

2023-01-25 11:04 UTC, angelocatalani commented on .github/workflows/main.yaml
> +
```suggestion
```

2023-01-25 11:06 UTC, angelocatalani requested changes

2023-01-25 11:06 UTC, angelocatalani commented on .github/actions/poetry/action.yaml
> +          shell: bash
```suggestion
          shell: bash

```

2023-02-01 15:20 UTC, soapwaster commented
lgtm

2023-02-01 15:22 UTC, soapwaster reviewed
wdyt

2023-02-01 15:31 UTC, soapwaster reviewed
wdyt

2023-02-02 08:56 UTC, angelocatalani approved these changes

2023-02-02 08:57 UTC, merged